# Generated by Django 5.2.7 on 2026-04-18 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresenceConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection_key', models.CharField(max_length=255, unique=True)),
                ('tab_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_interaction_at', models.DateTimeField()),
                ('last_heartbeat_at', models.DateTimeField()),
                ('connected_at', models.DateTimeField()),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_connections', to='accounts.usersession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='presence_us_user_id_166c3a_idx'), models.Index(fields=['user', 'disconnected_at'], name='presence_us_user_id_1ca17c_idx'), models.Index(fields=['last_heartbeat_at'], name='presence_us_last_he_212e44_idx')],
            },
        ),
    ]
