# Generated by Django 5.2.7 on 2026-04-18 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('binding_type', models.CharField(choices=[('unbound', 'Unbound'), ('room_message', 'Room Message'), ('dialog_message', 'Dialog Message')], default='unbound', max_length=16)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DialogMessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_message_bindings', to='attachments.attachment')),
                ('dialog_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_bindings', to='chat.dialogmessage')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_message_bindings', to='attachments.attachment')),
                ('room_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_bindings', to='chat.roommessage')),
            ],
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['uploaded_by_user'], name='attachments_uploade_882b84_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['binding_type'], name='attachments_binding_1dfc56_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['created_at'], name='attachments_created_722260_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='attachments_attachment_size_positive'),
        ),
        migrations.AddIndex(
            model_name='dialogmessageattachment',
            index=models.Index(fields=['dialog_message'], name='attachments_dialog__7af749_idx'),
        ),
        migrations.AddConstraint(
            model_name='dialogmessageattachment',
            constraint=models.UniqueConstraint(fields=('attachment',), name='attachments_dialogmessageattachment_unique_attachment'),
        ),
        migrations.AddConstraint(
            model_name='dialogmessageattachment',
            constraint=models.UniqueConstraint(fields=('dialog_message', 'attachment'), name='attachments_dialogmessageattachment_unique_pair'),
        ),
        migrations.AddIndex(
            model_name='roommessageattachment',
            index=models.Index(fields=['room_message'], name='attachments_room_me_ac4ba7_idx'),
        ),
        migrations.AddConstraint(
            model_name='roommessageattachment',
            constraint=models.UniqueConstraint(fields=('attachment',), name='attachments_roommessageattachment_unique_attachment'),
        ),
        migrations.AddConstraint(
            model_name='roommessageattachment',
            constraint=models.UniqueConstraint(fields=('room_message', 'attachment'), name='attachments_roommessageattachment_unique_pair'),
        ),
    ]
