# Generated by Django 5.2.7 on 2026-04-18 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('attachments', '0001_initial'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('room_created', 'Room Created'), ('room_updated', 'Room Updated'), ('room_deleted', 'Room Deleted'), ('member_removed', 'Member Removed'), ('member_banned', 'Member Banned'), ('member_unbanned', 'Member Unbanned'), ('admin_promoted', 'Admin Promoted'), ('admin_demoted', 'Admin Demoted'), ('peer_ban_created', 'Peer Ban Created'), ('peer_ban_removed', 'Peer Ban Removed'), ('message_deleted', 'Message Deleted'), ('session_revoked', 'Session Revoked')], max_length=32)),
                ('metadata_json', models.JSONField(default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events_performed', to=settings.AUTH_USER_MODEL)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to='attachments.attachment')),
                ('dialog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to='chat.dialog')),
                ('dialog_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.dialogmessage')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to='chat.room')),
                ('room_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.roommessage')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to='accounts.usersession')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['action_type'], name='audit_moder_action__02935e_idx'), models.Index(fields=['actor_user'], name='audit_moder_actor_u_95ebd6_idx'), models.Index(fields=['target_user'], name='audit_moder_target__92895a_idx'), models.Index(fields=['room'], name='audit_moder_room_id_7b840f_idx'), models.Index(fields=['created_at'], name='audit_moder_created_799927_idx')],
            },
        ),
    ]
