# Generated by Django 5.2.7 on 2026-04-18 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('frozen_reason', models.TextField(blank=True, null=True)),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs_high', to=settings.AUTH_USER_MODEL)),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs_low', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DialogMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.dialog')),
                ('reply_to_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.dialogmessage')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dialog_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DialogReadState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='chat.dialog')),
                ('last_read_dialog_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.dialogmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_read_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=16)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='owned_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('banned_by_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issued_room_bans', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='room_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_invitations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='chat.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=16)),
                ('joined_at', models.DateTimeField()),
                ('invited_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_memberships_invited', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('reply_to_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.roommessage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.room')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='room_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomReadState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_room_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.roommessage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_read_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='dialog',
            index=models.Index(fields=['user_low'], name='chat_dialog_user_lo_b4affe_idx'),
        ),
        migrations.AddIndex(
            model_name='dialog',
            index=models.Index(fields=['user_high'], name='chat_dialog_user_hi_e708c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='dialog',
            constraint=models.CheckConstraint(condition=models.Q(('user_low__lt', models.F('user_high'))), name='chat_dialog_canonical_order'),
        ),
        migrations.AddConstraint(
            model_name='dialog',
            constraint=models.UniqueConstraint(fields=('user_low', 'user_high'), name='chat_dialog_unique_pair'),
        ),
        migrations.AddIndex(
            model_name='dialogmessage',
            index=models.Index(fields=['dialog', 'created_at'], name='chat_dialog_dialog__44364d_idx'),
        ),
        migrations.AddIndex(
            model_name='dialogmessage',
            index=models.Index(fields=['sender_user'], name='chat_dialog_sender__509f60_idx'),
        ),
        migrations.AddIndex(
            model_name='dialogmessage',
            index=models.Index(fields=['reply_to_message'], name='chat_dialog_reply_t_494e92_idx'),
        ),
        migrations.AddIndex(
            model_name='dialogreadstate',
            index=models.Index(fields=['user'], name='chat_dialog_user_id_e3dfeb_idx'),
        ),
        migrations.AddIndex(
            model_name='dialogreadstate',
            index=models.Index(fields=['dialog'], name='chat_dialog_dialog__fbe1b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='dialogreadstate',
            constraint=models.UniqueConstraint(fields=('dialog', 'user'), name='chat_dialogreadstate_unique_pair'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['visibility'], name='chat_room_visibil_42a296_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['owner_user'], name='chat_room_owner_u_27f069_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['name'], name='chat_room_name_8fdd04_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='chat_room_name_not_empty'),
        ),
        migrations.AddIndex(
            model_name='roomban',
            index=models.Index(fields=['room'], name='chat_roomba_room_id_a092e1_idx'),
        ),
        migrations.AddIndex(
            model_name='roomban',
            index=models.Index(fields=['user'], name='chat_roomba_user_id_9090b9_idx'),
        ),
        migrations.AddIndex(
            model_name='roomban',
            index=models.Index(fields=['room', 'removed_at'], name='chat_roomba_room_id_a590bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomban',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='chat_roomban_unique_pair'),
        ),
        migrations.AddIndex(
            model_name='roominvitation',
            index=models.Index(fields=['room', 'status'], name='chat_roomin_room_id_bf9406_idx'),
        ),
        migrations.AddIndex(
            model_name='roominvitation',
            index=models.Index(fields=['invited_user', 'status'], name='chat_roomin_invited_603a13_idx'),
        ),
        migrations.AddConstraint(
            model_name='roominvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('room', 'invited_user'), name='chat_roominvitation_one_pending_per_room_user'),
        ),
        migrations.AddIndex(
            model_name='roommembership',
            index=models.Index(fields=['room'], name='chat_roomme_room_id_c9df36_idx'),
        ),
        migrations.AddIndex(
            model_name='roommembership',
            index=models.Index(fields=['user'], name='chat_roomme_user_id_def2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='roommembership',
            index=models.Index(fields=['room', 'role'], name='chat_roomme_room_id_37d57f_idx'),
        ),
        migrations.AddConstraint(
            model_name='roommembership',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='chat_roommembership_unique_pair'),
        ),
        migrations.AddIndex(
            model_name='roommessage',
            index=models.Index(fields=['room', 'created_at'], name='chat_roomme_room_id_4549eb_idx'),
        ),
        migrations.AddIndex(
            model_name='roommessage',
            index=models.Index(fields=['sender_user'], name='chat_roomme_sender__6a992d_idx'),
        ),
        migrations.AddIndex(
            model_name='roommessage',
            index=models.Index(fields=['reply_to_message'], name='chat_roomme_reply_t_b05b89_idx'),
        ),
        migrations.AddIndex(
            model_name='roomreadstate',
            index=models.Index(fields=['user'], name='chat_roomre_user_id_768dac_idx'),
        ),
        migrations.AddIndex(
            model_name='roomreadstate',
            index=models.Index(fields=['room'], name='chat_roomre_room_id_d1d18d_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomreadstate',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='chat_roomreadstate_unique_pair'),
        ),
    ]
